### ISSUE TITLE
other installation method

### ISSUE THREAD

**Issue by terrybakshi** [zipMoney/magento2#44]
Hi is there any method to install this extension rather than using composer to install it.

**Comment by benzhangzip** [comment]
Hi Terrybakshi,
It is totally possible first you need to download 2 repository from github:
Magento2 Extension:
https://github.com/zipMoney/magento2/

Zip PHP SDK
https://github.com/zipMoney/merchantapi-php

Both master branch should be OK
Put all the files from Magento2 Extension to:
/Magento2RootFolder/app/code/Zipmoney/ZipmoneyPayment
you might need to create new folder Zipmoney/ZipmoneyPayment

copy all the files from Zip PHP SDK to:
/Magento2RootFolder/lib/internal/Zipmoney
you will need to create folder Zipmoney (this folder name doesn't matter you could also use merchantapi-php)

Then you need to modify a PHP file
/app/code/Zipmoney/ZipmoneyPayment/registration.php

`<?php
require_once(BP . "/lib/internal/Zipmoney/autoload.php");
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'ZipMoney_ZipMoneyPayment',
    __DIR__
); `

Only add the require_once(BP . "/lib/internal/Zipmoney/autoload.php");  here require_once is used instead of include_once as we want to throw error if you did not put the file in the lib folder correctly, as we do have hard dependence on the SDK.

You will still need to run the Magento command line to update database schema to add some "required" columns in your quote and order and payment tables

`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`

to make sure all possible rewrite code and dependency injection code get generated.
Hope this helps.

**Comment by benzhangzip** [comment]
Issue resolved

**Comment by Orims14** [comment]
Hi @benzhangzip how do you call the class in your model?

Thank You

**Comment by benzhangzip** [comment]
Hi @Orims14,
The code loaded from library folder /lib/internal/Zipmoney/autoload.php is custom autoloader similar to composer autoloader that support only PSR-4 autoload so in your model or class you could use code like:
`
use \ZipMoney\ZipMoneyPayment\Model\Config;

$config = new Config();
// or directly reference
$config = new \ZipMoney\ZipMoneyPayment\Model\Config();
`
For more information you could checkout our SDK repo https://github.com/zipMoney/merchantapi-php which current repo has dependency on that SDK and you could find all classes you need. Hope this helps.
