### ISSUE TITLE
Is it compatible with Magento 2.3 

### ISSUE THREAD

**Issue by 3615helloworld** [zipMoney/magento2#48]
Hi, Is it compatible with Magento 2.3 ? Thanks

**Comment by benzhangzip** [comment]
Hi @3615helloworld ,

We have briefly tested the plugin is compatible with Magento 2.3 version and it is working as expected, there are some known issue of Magento 2.3 itself:

- Magento 2.3 Blank Page in Windows server deal to the folder path \ and / issue but Magento only check / Linux version. (if running in Linux no issue)
The fix is in here: https://stackoverflow.com/questions/53565012/blank-admin-page-after-installing-magento-2-3-on-windows-10

For Zip Payment plugin it should be compatible to Magento 2.3 as this version did not change much on payment end. Some issues when you are using Magento2 OneStepCheckout module which move the Payment continue button to the order review section, as each payment could have its own place order callback JS function unfortunately our one is using different name than placeOrder() callback which is not compatible for those OneStepCheckout module that only call placeOrder(), we will work on this, but generally it is working.

Please let us know if there is any issue when installed with Mageno2.3 we need more feedback from developers and we provide a better robust extension early 2019. 

Thanks.

**Comment by stephenbori** [comment]
@benzhangzip  - In reference to my post on issue here  https://github.com/zipMoney/magento2/issues/56#issuecomment-484539422 we are utilising the onestepcheckout provided by amasty... could this be a factor in the cart not working?

**Comment by benzhangzip** [comment]
We did not test the amasty onestepcheckout as we don't have their extension, but we do have merchants using that extension and working, just need to make sure you using the latest version of this extension, and latest extension of zipmoney, as we will keep fixing compatibility issue when Magento2 changes.
Closing this issue.
