### ISSUE TITLE
Error after upgrading to Magento 2.3.2

### ISSUE THREAD

**Issue by thanura** [zipMoney/magento2#61]
A JS error appears in checkout after upgrading to Magento 2.3.2
![Screen Shot 2019-10-17 at 3 08 15 pm](https://user-images.githubusercontent.com/1555470/66977862-482ae280-f0f3-11e9-9632-3135b6d2ee36.png)

**Comment by benzhangzip** [comment]
Hi Thanura,

Thank you for reporting this error, it is legacy issue that our old widget JS is poorly written by our previous developers, but since Oct 2018, we completely rebuilt the widget JS that no more need to run any initialization code in all plugins, as we don't have time to clean up all plugins, could you feel free to remove the code in
/vendor/zipmoney/magento2/view/frontend/web/template/payment/zipmoney.html
(about line 18)
![image](https://user-images.githubusercontent.com/42924127/68440194-4f3e9f80-021e-11ea-952f-aad6cba8154f.png)

You need to complete remove it and run static content deploy

Also you could remove the code in vendor\zipmoney\magento2\view\frontend\web\js\view\payment\method-renderer\zipmoney-zipmoneypayment.js
![image](https://user-images.githubusercontent.com/42924127/68440287-a17fc080-021e-11ea-9e21-d8965baafd92.png)

That function is no longer needed, then you will have no console error anymore in checkout page, hope this helps, and we will update this bug later once we have time to fix other issue together. Hope this helps

**Comment by thanura** [comment]
Thanks, I have just updated the module to 1.0.9

**Comment by benzhangzip** [comment]
This issue is fixed in the new release 1.0.10 please update the package to get this fix, mainly affecting 2.3.x Magento users. It will not break the site but just error warning in checkout does not look good, will close this issue as resolved. Thanks
