### ISSUE TITLE
Cannot checkout in sandbox environment

### ISSUE THREAD

**Issue by aligent-lturner** [zipMoney/magento2#69]
Previously, we have not had any issues checking out in a sandbox environment.
Recently, however (I'm not able to say exactly when the problem started), the `assets` call fails with a 400 error.
I believe this is because `zip-widget.min.js` is attempting to call `api.zipmoney.com.au` instead of `api.sandbox.zipmoney.com.au`, and this results in the error `Cannot find the merchant or unregistered`.
If I perform a curl request with the same merchant id to the sandbox URL, the call is successful.

I assume that either the `zip-widget.min.js` script has changed recently and doesn't take the environment into account, or that the call that's getting `zip-widget.min.js` is getting the wrong version.

I realise that this isn't necessarily an issue solely with the Magento 2 extension, but there's not really anywhere else to raise it.

**Comment by HenryFan-Zip** [comment]
@aligent-lturner 

Sorry for any inconvenience.

We already noticed and applied a hotfix today. The issue was introduced by previous widget release (v2.4.2) 4 days ago. Sandbox API endpoint was removed accidently. 

This issue should be fixed now. Widget JS is able to switch production / sandbox API endpoint using env flag. Please try again and let us know if you still have same issue.

Thank you for your report. 
Appreciate your support and helps!
