### ISSUE TITLE
Replace checkouttitle on html

### ISSUE THREAD

**Issue by purvid0204** [zipMoney/magento2#75]
Hello,

Can i replace data-zm-asset="checkouttitle" to data-zm-asset="checkouttitle zip"  in zipmoney.html.is it any effect in functionality?

Why checkoutitle remove zip text?when has it remove?

Please reply as early as possible.

**Comment by benzhangzip** [comment]
Hi @purvid0204 this syntax is for our widget.js code to dynamically replaced the "zip" text with the logo image on the fly, the attribute data-zm-asset is used internally and your changes might works, but better one is remove all the data-zm-* attribute for the element, so that our widget will not try to replace the name or title in the checkout text.

Hope this helps
