### ISSUE TITLE
An error occurred while getting the redirect url from zipMoney.

### ISSUE THREAD

**Issue by distillerydave** [zipMoney/magento2#82]
I am pretty new to Magento and struggling to debug this one. 

I am using Magento 2.4 & the latest release of zipMoney/Magento2

Having selected zipmoney at the checkout with a real Australian adddress & phone number, I click continue and get the error

**An error occurred while getting the redirect url from zipMoney.**

Configuration as below, Public key & private key taken from the zipmoney sandbox account

<img width="1014" alt="zipmoney_config" src="https://user-images.githubusercontent.com/71106906/92833279-d26ceb00-f417-11ea-9f4d-593f7facd4cc.png">

**Comment by distillerydave** [comment]
Looks like my problem was that I wasn't using AUD for the currency config.

**Comment by androshchuk** [comment]
I have the same error with the sandbox environment. 
It turned out that the client provided incorrect keys (provided for the production environment).
The description of the error from API is not at all informative and took a long time to fix this problem.
I hope someone will find it useful.

Regards
